language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    # Note that the tools section appears twice on purpose as it’s required to get the newest Android SDK tools.

    - build-tools-25.0.3
    - android-21
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - ./gradlew assembleRelease
  - ./gradlew test

